### ISSUE TITLE
Minus

### ISSUE THREAD

**Issue by Fak1e** [Szczypioreg/LibPLUS#1]
Jeśli w ocenach jest "-" to nie liczy średniej, pokazuje NaN, nawet jeśli jest tylko jeden minus w ocenach z danego przedmiotu

**Comment by Szczypioreg** [comment]
Dziękuje za zgłoszenie @Fak1e. 
Proszę sprawdź czy na nowej wersji 1.3 również występuje problem.
http://i.imgur.com/ruBNkY2.png

**Comment by Fak1e** [comment]
Jeśli są same minusy to dalej jest NaN
http://i.imgur.com/HeXRr6K.png

**Comment by Szczypioreg** [comment]
Źle zrozumiałem. Teraz problem powinien być rozwiązany. Wersja 1.6.
